name = "Riskitera"
license = "Proprietary"
licenselink = ""
description = "Custom dark theme for Riskitera Blog"
homepage = "https://blog.riskitera.com"
min_version = "0.120.0"

[author]
  name = "Riskitera Team"
